name: just
description: One very lightweight state management library for Flutter
version: 0.0.2
repository: https://github.com/linyongsheng/just
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
