name: just
description: A very lightweight state management library.
version: 1.0.19
repository: https://github.com/linyongsheng/just
homepage:

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
